name: "Build Node Package"

on:
  push:
    tags:
      - 'v*'

jobs:
  build_cfg:
    runs-on: ubuntu-latest
    env:
      VERSION_STR: ${{ github.ref_name }}
    outputs:
      VERSION_STR: ${{ steps.config_step.outputs.VERSION_STR }}
    steps:
      - name: "Get Version STR"
        id: config_step
        run: |-
          echo "VERSION_STR=${VERSION_STR}" >> $GITHUB_OUTPUT

  build_node_app:
    needs: [build_cfg]
    name: "Build node tarball with tag [${{ needs.build_cfg.outputs.VERSION_STR }}]"
    uses: ./.github/workflows/util-build-node-app.yml
    secrets: inherit
    with:
      version_str: ${{ needs.build_cfg.outputs.VERSION_STR }}
