name: "Build Node Package"

on:
  push:
    tags:
      - 'v*'

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: "Trigger Node Build"
        uses: peter-evans/repository-dispatch@latest
        with:
          token: ${{ secrets.CI_WEBHOOK_TOKEN }}
          repository: istresearch/ci-docker
          event-type: build-node-app
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "ref_type": "${{ github.ref_type }}",
                "ref_name": "${{ github.ref_name }}"
              },
              "node": {
                "version": "12.x",
                "arch_allowed": "amd64 arm64",
                "install_sh": "ci_yarn_install.sh",
                "output_folder": "build"
              },
              "filerepo": {
                "file_name": "floweditor-${{ github.ref_name }}",
                "dst_folder": "/data/repo/engage/floweditor"
              },
              "callback": {
                "repository": "${{ github.repository }}",
                "event_type": "build_node_success",
                "error_type": "build_node_error"
              }
            }
  #endjob trigger-build
